import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";

const jetbrainsMono = localFont({
  src: "../public/font/jetbrains-mono/jetbrains-mono-variable.ttf",
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jetbrainsMono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col gap-4">
        NAV
        <div className="gap-10 px-4 py-8 md:px-6 md:py-12 lg:gap-8 lg:px-8 lg:py-12 items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
